### ISSUE TITLE
Test Contradicts Instructions

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-pip-lab#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204243?module_item_id=467999

### Concern

Not sure if this has already been addressed, but the test expects students to have installed the `2.25.0` version of requests, while the instructions tell them to install the `2.27.1` version.

**Comment by professor-ben** [comment]
I'll double check on this! I seem to remember the intention being to change versions around, but I may need to clarify that if it's the case.

**Comment by professor-ben** [comment]
The issue here, turns out, was that I updated this and the Canvas gem did not sync it. We're working on a couple of updates, but this should be synced the Monday after Thanksgiving.

Thanks again for keeping an eye out,
Ben

**Comment by Matt-Eva** [comment]
Of course, thanks Ben!
